### ISSUE TITLE
Why is there a var_dump in SimpleMailInvoker?

### ISSUE THREAD

**Issue by Lefthandmedia** [Magnatron/modSwiftMailer#1]
Hi, i'm trying to get MSM to work and stumble upon a var dump in
https://github.com/Magnatron/modSwiftMailer/blob/master/core/model/modx/mail/swiftmailer/model/swiftmailer/classes/Swift/Transport/SimpleMailInvoker.php line 49
 Why is this var_dump when safe_mode is off?

**Comment by CyntaxDotDev** [comment]
You can safely remove that dump from your code and keep your code still updateable. ;) I guess it got there through debugging and thus is not meant to be there.
